[package]
name = "derive-masked"
version = "0.0.0"
authors = ["okcodes <code@ok.codes>"]
edition = "2021"
description = "Adds #[derive(x)] macros for implementing the Debug and Display traits masking out sensitive fields"
license = "MIT OR Apache-2.0"
repository = "https://github.com/okcodes/derive-masked"
documentation = "https://docs.rs/derive-masked"
homepage = "https://github.com/okcodes/derive-masked"

[dependencies]
quote = "1.0.36"
syn = "2.0.67"

[lib]
proc-macro = true
